### ISSUE TITLE
不断产生子进程,没有关闭....怎么破....

### ISSUE THREAD

**Issue by ql2005** [huyanping/php_crontab#10]
OSX+NGINX+PHP-FPM 开发环境
用Daemon或者HttpDaemon运行, 不停的产生php-fpm子进程,没有关闭,CPU负载越来越高~~

![php-fpm子进程](http://ww4.sinaimg.cn/mw690/c0ff24a9gw1fben1fdfi8j20i80bvdit.jpg)

尝试 kill getmypid 未果....怎么办

**Comment by huyanping** [comment]
php-fpm是php的cgi进程管理器，跟httpDaemon并没有关系。不是httpDaemon启动的。可以查看下ppid就知道了

**Comment by ql2005** [comment]
不是httpDaemon 里 pcntl_fork 出来的么?..

**Comment by huyanping** [comment]
不是～是php-fpm，另外一个东西

**Comment by ql2005** [comment]
我在web程序里执行的 new HttpDaemon , 他父级的进程就是 php-fpm哇,
为了排除干扰, 'cmd' => 'ls -al',
也只有在运行这个的时候会产生这么多 php-fpm的子进程..

**Comment by huyanping** [comment]
php-fpm下不能使用pcntl扩展的

**Comment by ql2005** [comment]
原来只是认为fpm下跑不了pcntl扩展~没想到是会带来一些问题~
现在另外写了脚本,然后用exec来运行
终于在页面上实现了对crontab的管理

**Comment by huyanping** [comment]
👍
