### ISSUE TITLE
测试启动example中的http_daemon.php报参数类型错误

### ISSUE THREAD

**Issue by cooperx7** [huyanping/php_crontab#3]
错误如下：
[root@localhost example]# php http_daemon.php
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Jenner\Crontab\HttpDaemon::crontabCallback() must be an instance of Jenner\Crontab\Crontab, instance of React\EventLoop\Timer\Timer given in /root/vendor/jenner/crontab/src/Jenner/Crontab/HttpDaemon.php:58
Stack trace:
#0 [internal function]: Jenner\Crontab\HttpDaemon->crontabCallback(Object(React\EventLoop\Timer\Timer))
#1 /root/vendor/jenner/crontab/vendor/react/event-loop/Timer/Timers.php(90): call_user_func(Array, Object(React\EventLoop\Timer\Timer))
#2 /root/vendor/jenner/crontab/vendor/react/event-loop/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#3 /root/vendor/jenner/crontab/src/Jenner/Crontab/HttpDaemon.php(52): React\EventLoop\StreamSelectLoop->run()
#4 /root/vendor/jenner/crontab/example/http_daemon.php(34): Jenner\Crontab\HttpDaemon->start()
#5 {main}
  thrown in /root/vendor/jenner/crontab/src/Jenner/Crontab/HttpDaemon.php on line 58

**Comment by huyanping** [comment]
可以提供一些php版本和扩展列表吗？
