### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by xiaoloner** [huyanping/php_crontab#4]
Call to undefined function Jenner\SimpleFork\pcntl_signal()
错误位置
FILE: /home/wwwroot/vendor/jenner/simple_fork/src/Process.php 　LINE: 234

**Comment by huyanping** [comment]
缺少pcntl扩展吧？

**Comment by xiaoloner** [comment]
确实是少了pcntl扩展，而且windows下不支持该扩展
