### ISSUE TITLE
我想知道 可以通过这个程序删除与编辑定时任务吗？ 可以的话该如何操作呢？可否提供示例？

### ISSUE THREAD

**Issue by lovefuwei** [huyanping/php_crontab#6]
如题

**Comment by huyanping** [comment]
这个程序更多的是一个包，提供的主要功能是读取定时任务配置（不关心配置从哪里来的），执行定时任务。如果你希望对定时任务进行修改，可以将定时任务写入文件然后更新文件。或者使用http daemon的方式运行（不推荐）。
